# Generated by Django 5.2.6 on 2026-04-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customergeneralpayment_creditpayment_general_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cedula',
            field=models.CharField(blank=True, help_text='Número de cédula (V-XXXXXXXX o E-XXXXXXXX)', max_length=15, null=True, unique=True, verbose_name='Cédula'),
        ),
    ]
