# Generated by Django 5.2.6 on 2026-09-07 14:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('start_time', models.TimeField(verbose_name='Hora de entrada')),
                ('end_time', models.TimeField(verbose_name='Hora de salida')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalScheduleException',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Desde')),
                ('date_end', models.DateField(verbose_name='Hasta')),
                ('exception_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('permission', 'Permiso'), ('sick', 'Enfermedad'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Detalle (opcional)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Registrado el')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Excepción de Horario',
                'verbose_name_plural': 'historical Excepciones de Horario',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalShift',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('start_time', models.TimeField(verbose_name='Hora de entrada')),
                ('end_time', models.TimeField(verbose_name='Hora de salida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Turno',
                'verbose_name_plural': 'historical Turnos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Desde')),
                ('date_end', models.DateField(verbose_name='Hasta')),
                ('exception_type', models.CharField(choices=[('vacation', 'Vacaciones'), ('permission', 'Permiso'), ('sick', 'Enfermedad'), ('other', 'Otro')], max_length=20, verbose_name='Tipo')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Detalle (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Registrado el')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_schedule_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Excepción de Horario',
                'verbose_name_plural': 'Excepciones de Horario',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalShiftAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='schedules.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'historical Asignación de Turno',
                'verbose_name_plural': 'historical Asignaciones de Turno',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='schedules.shift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'ordering': ['date', 'shift'],
                'unique_together': {('date', 'shift')},
            },
        ),
    ]
