# Generated by Django 5.2.6 on 2026-08-08 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_product_cat_active_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('in_progress', 'En Progreso'), ('completed', 'Completado')], default='completed', max_length=15, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('category', models.ForeignKey(blank=True, help_text='Vacío si el conteo fue de todas las categorías', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='inventory.category', verbose_name='Categoría')),
                ('counted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Realizado por')),
            ],
            options={
                'verbose_name': 'Conteo de Inventario',
                'verbose_name_plural': 'Conteos de Inventario',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_stock', models.DecimalField(decimal_places=3, help_text='Snapshot de Product.stock al momento del conteo', max_digits=10, verbose_name='Stock del Sistema')),
                ('physical_stock', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Stock Físico Contado')),
                ('difference', models.DecimalField(decimal_places=3, help_text='physical_stock - system_stock; negativo = falta stock', max_digits=10, verbose_name='Diferencia')),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycount', verbose_name='Conteo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_items', to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Conteo',
                'verbose_name_plural': 'Ítems de Conteo',
                'ordering': ['product__name'],
                'unique_together': {('count', 'product')},
            },
        ),
    ]
