# Generated by Django 5.2.6 on 2026-08-08 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventorycount_inventorycountitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='corrections_applied_at',
            field=models.DateTimeField(blank=True, help_text='Si tiene valor, ya se generaron los InventoryAdjustment de este conteo — no volver a aplicar', null=True, verbose_name='Correcciones Aplicadas El'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='corrections_applied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_corrections', to=settings.AUTH_USER_MODEL, verbose_name='Correcciones Aplicadas Por'),
        ),
    ]
