# Generated by Django 5.2.6 on 2026-09-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_inventorycount_corrections_applied_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='pricing_mode',
            field=models.CharField(choices=[('usd', 'USD (precio en Bs se calcula con la tasa BCV)'), ('bs_fixed', 'Precio estable en Bs (no se recalcula con la tasa)')], default='usd', help_text="'usd': el precio en Bs se recalcula con la tasa BCV en cada venta (comportamiento por defecto). 'bs_fixed': selling_price_bs es la fuente de verdad, no se toca al cambiar la tasa. Solo aplica al precio de VENTA — el de compra siempre sigue en USD.", max_length=10, verbose_name='Modo de precio'),
        ),
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('usd', 'USD (precio en Bs se calcula con la tasa BCV)'), ('bs_fixed', 'Precio estable en Bs (no se recalcula con la tasa)')], default='usd', help_text="'usd': el precio en Bs se recalcula con la tasa BCV en cada venta (comportamiento por defecto). 'bs_fixed': selling_price_bs es la fuente de verdad, no se toca al cambiar la tasa. Solo aplica al precio de VENTA — el de compra siempre sigue en USD.", max_length=10, verbose_name='Modo de precio'),
        ),
    ]
